### ISSUE TITLE
опечатка в algebra.pdf

### ISSUE THREAD

**Issue by semrosin** [vlapugb/-2024-2025#1]
![изображение_2024-09-23_202304173](https://github.com/user-attachments/assets/756d4807-22cf-4325-9ea4-4a84f4e56733)

наверное, вместо t должен быть y? Это самое начало, про классы эквивалентности

**Comment by vlapugb** [comment]
Да, тут $y$ заместо $t$, сможешь пожалуйста, сделать pull request на изменение этой опечатки?
